# Generated by Django 4.2.5 on 2026-02-15 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationparticipant',
            name='is_pinned',
        ),
    ]
