# Generated by Django 4.2.5 on 2026-02-16 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_remove_conversationparticipant_is_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationparticipant',
            name='deleted',
        ),
        migrations.AddField(
            model_name='conversation',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('private', 'Личный'), ('group', 'Групповой'), ('favorite', 'Избранное')], max_length=10),
        ),
        migrations.CreateModel(
            name='FileMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat_files/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='chat.message')),
            ],
        ),
    ]
